config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "articles#index"

  resources :articles do
    resources :comments
  end

  get "signup" => "users#new"
  resources :users

  get "login" => "sessions#new"
  post "login" => "sessions#create"

  delete "logout" => "sessions#destroy"
  
  mount Sidekiq::Web => '/sidekiq'
  

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
require 'elasticsearch/model'

class Article < ApplicationRecord
  include Elasticsearch::Model
  settings index: {} do
    mappings dynamic: 'false' do
      indexes :title
      indexes :body,
      analyzer: 'english',
      index_options: 'offsets'
    end
  end

  def reindex
    IndexJob.perform_async(id)
  end

  after_commit :reindex

  has_many :comments, dependent: :destroy
  has_many :parent_comments, -> { where "parent_comment_id is null" }, class_name: 'Comment'

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  has_many :comments, foreign_key: "parent_comment_id"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :comments
  has_secure_password

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :require_user, only: [:index, :show]

  def index
    if params[:search]
      @articles = Article.search(params[:search]).records
    else
      @articles = Article.all
    end
  end

  def show
    @article = Article.includes(parent_comments: [:comments, :user]).find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to (@article)
    else
      render :edit, status: unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])

    comment_data = comment_params
    comment_data[:user_id] =  current_user.id

    @comment = @article.comments.create(comment_data)
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:body, :parent_comment_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    @user = User.find_by_email(params[:session][:email])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      session[:user_id] = @user.id
      redirect_to "/"
    else
      redirect_to "/signup"
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title%><br>
    <%= form.text_field :title%>
    <% article.errors.full_messages_for(:title).each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body%><br>
    <%= form.text_field :body%>
        <% article.errors.full_messages_for(:body).each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article%>

app/views/articles/index.html.erb
  <% if current_user %>
    <%= link_to "Logout", logout_path, data: {turbo_method: :delete}  %>
  <% end %>

  <%= form_tag(root_path, method: :get) do  %>
    <div>
      <%= text_field_tag 'search' %>
      <%= submit_tag 'Search' %>
    </div>
  <% end %>

  <h1>Hello, Rails</h1>
    <ul>
    <% @articles.each do |article| %>
      <li>
        <%= link_to article.title, article%>
      </li>
    <% end %>
  </ul>

<% if current_user %>

  <%= link_to "New Article", new_article_path %>

  <% else %>
    <ul>
      <li><%= link_to "Login", login_path %></li>
      <li><%= link_to "Signup", signup_path %></li>
    </ul>

<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h1><%= @article.body %></h1>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li>
    <%= link_to "Destroy", article_path(@article), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </li>
</ul>

<h2>Comments</h2>
<ul class="list-group">
  <% @article.parent_comments.each do |comment|%>
    <%= render :partial => "comments/comment", :locals => { :comment => comment } %>
  <% end %>
</ul>

<h2>Add a comment:</h2>

<%= form_with model: [@article, @article.comments.build] do |form|%>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_comment.html.erb
<li class="list-group-item">
  <%= comment.user&.full_name || comment.commenter %>
  <br>
  <%= comment.body %>
  <button type="button" class="btn btn-secondary" data-bs-toggle="collapse" data-bs-target="#comment-<%=comment.id%>" aria-expanded="false" aria-controls="comment-<%=comment.id%>">Reply</button>
  <div class="collapse" id="comment-<%=comment.id%>">
    <%= form_for :comment, url: article_comments_path(@article.id) do |f| %>
      <%= f.text_area :body %><br />
      <%= f.hidden_field :parent_comment_id, :value => comment.id %>
      <%= f.submit %>
    <% end %>
  </div>
  <ul class="list-group">
    <% comment.comments.each do |reply|%>
      <%= render :partial => "comments/comment", :locals => { :comment => reply } %>
    <% end %>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |form| %>
  <div>
    <%= form.label :first_name%><br>
    <%= form.text_field :first_name%>
    <% @user.errors.full_messages_for(:first_name).each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :last_name%><br>
    <%= form.text_field :last_name%>
    <% @user.errors.full_messages_for(:last_name).each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email%><br>
    <%= form.text_field :email%>
    <% @user.errors.full_messages_for(:email).each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password%><br>
    <%= form.password_field :password%>
    <% @user.errors.full_messages_for(:password).each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>